## Tutorial for Applying SoccerCPD to kloppy Data

In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import rpy2.robjects.packages as rpackages

from src.kloppy import Kloppy
from src.soccercpd import SoccerCPD

In [2]:
utils = rpackages.importr('utils')
utils.chooseCRANmirror(ind=1)
if not rpackages.isinstalled('gSeg'):
    utils.install_packages('gSeg')
rpackages.importr('gSeg')

rpy2.robjects.packages.Package as a <module 'gSeg'>

### Converting preprocessed RGP data into SoccerCPD format

In [3]:
home_id = 79852
away_id = 79921
data = pd.read_csv(f"data/kloppy/{home_id}-{away_id}.csv", header=0, parse_dates=["datetime"])
col_dict = {"index": "frame_id", "session": "period_id", "time": "timestamp"}
data = data.reset_index().rename(columns=col_dict)
data

,frame_id,datetime,period_id,timestamp,home_phase,away_phase,home_18_x,home_18_y,home_18_speed,home_22_x,...,away_26_speed,away_28_x,away_28_y,away_28_speed,away_30_x,away_30_y,away_30_speed,away_33_x,away_33_y,away_33_speed
0,0,2024-09-28 05:00:00.000,1,0.0,1,1,-11.759193,2.137559,0.941,-9.194458,...,NaN,NaN,NaN,NaN,23.639926,-2.356231,0.000,22.313197,-1.537077,0.462
1,1,2024-09-28 05:00:00.100,1,0.1,1,1,-11.777115,2.137514,0.615,-9.212372,...,NaN,NaN,NaN,NaN,23.639926,-2.356231,0.160,22.313189,-1.522390,0.300
2,2,2024-09-28 05:00:00.200,1,0.2,1,1,-11.795029,2.122782,0.645,-9.212372,...,NaN,NaN,NaN,NaN,23.639926,-2.356231,0.085,22.295275,-1.537122,0.307
3,3,2024-09-28 05:00:00.300,1,0.3,1,1,-11.795020,2.108095,0.417,-9.194441,...,NaN,NaN,NaN,NaN,23.639917,-2.341544,0.000,22.295266,-1.522435,0.465
4,4,2024-09-28 05:00:00.400,1,0.4,1,1,-11.777107,2.122827,0.134,-9.212372,...,NaN,NaN,NaN,NaN,23.657848,-2.356186,0.089,22.295266,-1.522435,0.058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47395,47395,2024-09-28 06:30:59.500,2,2339.5,3,5,NaN,NaN,NaN,-2.191908,...,15.360,-15.195369,-6.213212,8.390,NaN,NaN,NaN,NaN,NaN,NaN
47396,47396,2024-09-28 06:30:59.600,2,2339.6,3,5,NaN,NaN,NaN,-2.317312,...,18.849,-15.231050,-6.492353,9.412,NaN,NaN,NaN,NaN,NaN,NaN
47397,47397,2024-09-28 06:30:59.700,2,2339.7,3,5,NaN,NaN,NaN,-2.424820,...,18.611,-15.284687,-6.712791,8.375,NaN,NaN,NaN,NaN,NaN,NaN
47398,47398,2024-09-28 06:30:59.800,2,2339.8,3,5,NaN,NaN,NaN,-2.514370,...,17.421,-15.320377,-6.977245,9.598,NaN,NaN,NaN,NaN,NaN,NaN
47399,47399,2024-09-28 06:30:59.900,2,2339.9,3,5,NaN,NaN,NaN,-2.657705,...,20.714,-15.356049,-7.271072,10.898,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
kloppy = Kloppy(data)
kloppy.rotate_pitch()
input_data = kloppy.convert_to_soccercpd_input(exclude_gks=False)
input_data

                     datetime  team  player_id  player_period  session    time          x         y  speed
0     2024-09-28 05:00:00.000  away          6              1        1     0.0 -23.191456  1.652376  0.197
1     2024-09-28 05:00:00.100  away          6              1        1     0.1 -23.173542  1.667108  0.704
2     2024-09-28 05:00:00.200  away          6              1        1     0.2 -23.155620  1.667153  0.513
3     2024-09-28 05:00:00.300  away          6              1        1     0.3 -23.137698  1.667198  0.704
4     2024-09-28 05:00:00.400  away          6              1        1     0.4 -23.137698  1.667198  0.674
...                       ...   ...        ...            ...      ...     ...        ...       ...    ...
47395 2024-09-28 06:30:59.500  home         46              3        2  2339.5  12.577387  8.483140  3.827
47396 2024-09-28 06:30:59.600  home         46              3        2  2339.6  12.631059  8.644830  5.779
47397 2024-09-28 06:30:59.700  home         46              3        2  2339.7  12.720567  8.821297  6.962
47398 2024-09-28 06:30:59.800  home         46              3        2  2339.8  12.828014  8.968435  6.863
47399 2024-09-28 06:30:59.900  home         46              3        2  2339.9  12.935462  9.115573  7.024

[1090200 rows x 9 columns]

### Converting kloppy data into SoccerCPD format

In [ ]:
data = pd.read_pickle("data/kloppy/sample_kloppy_file.pkl")
data

,period_id,timestamp,frame_id,ball_state,ball_owning_team_id,ball_x,ball_y,ball_z,ball_speed,home_250042780_x,...,away_250105686_d,away_250105686_s,home_250132399_x,home_250132399_y,home_250132399_d,home_250132399_s,home_250146926_x,home_250146926_y,home_250146926_d,home_250146926_s
0,1,0 days 00:00:00.012526,0,In,None,-0.102770,-0.341014,0.218483,2.095251,-49.963806,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0 days 00:00:00.052526,1,In,None,-0.151340,-0.406673,0.213257,2.045958,-49.961674,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,0 days 00:00:00.092526,2,In,None,-0.192688,-0.466049,0.207688,1.814223,-49.958416,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,0 days 00:00:00.132526,3,In,None,-0.216528,-0.521216,0.210978,1.504685,-49.957661,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,0 days 00:00:00.172526,4,In,Poland,-0.241989,-0.581856,0.210067,1.644357,-49.958775,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133848,2,0 days 01:29:59.800000,134995,In,Poland,27.218003,12.678193,19.303439,5.200775,-25.788414,...,0.068274,1.706862,20.570339,6.820256,0.074778,1.869440,31.127176,-5.250538,0.026990,0.674758
133849,2,0 days 01:29:59.840000,134996,In,Poland,27.098542,12.785913,19.159118,5.402708,-25.770994,...,0.070400,1.760004,20.541334,6.891814,0.077213,1.930313,31.119009,-5.224920,0.026888,0.672212
133850,2,0 days 01:29:59.880000,134997,In,Poland,26.979120,12.892536,19.001372,5.618840,-25.753012,...,0.071731,1.793281,20.511772,6.965704,0.079585,1.989621,31.109913,-5.198496,0.027946,0.698655
133851,2,0 days 01:29:59.920000,134998,In,Poland,26.859591,12.998185,18.830347,5.846915,-25.734995,...,0.075364,1.884089,20.481655,7.040879,0.080989,2.024713,31.101923,-5.171621,0.028037,0.700928
133852,2,0 days 01:29:59.960000,134999,In,Poland,26.739812,13.102983,18.646193,6.084951,-25.718691,...,0.080502,2.012541,20.450691,7.116075,0.081321,2.033035,31.096189,-5.144443,0.027777,0.694423

In [20]:
kloppy = Kloppy(data)
kloppy.preprocess_times()
kloppy.round_change_times()
kloppy.label_player_periods()
input_data = kloppy.convert_to_soccercpd_input()
input_data

                      datetime  team  player_id  player_period  session     time          x          y     speed
0      2024-01-01 01:00:00.000  away  250002096              1        1     0.00   0.233449 -14.192799  0.000000
1      2024-01-01 01:00:00.040  away  250002096              1        1     0.04   0.284003 -14.194001  1.264207
2      2024-01-01 01:00:00.080  away  250002096              1        1     0.08   0.335943 -14.194717  1.298633
3      2024-01-01 01:00:00.120  away  250002096              1        1     0.12   0.393036 -14.193744  1.427516
4      2024-01-01 01:00:00.160  away  250002096              1        1     0.16   0.458015 -14.194160  1.624524
...                        ...   ...        ...            ...      ...      ...        ...        ...       ...
134995 2024-01-01 02:29:59.800  home  250146926              5        2  2699.80  31.127176  -5.250538  0.674758
134996 2024-01-01 02:29:59.840  home  250146926              5        2  2699.84  31.119009  -5.224920  0.672212
134997 2024-01-01 02:29:59.880  home  250146926              5        2  2699.88  31.109913  -5.198496  0.698655
134998 2024-01-01 02:29:59.920  home  250146926              5        2  2699.92  31.101923  -5.171621  0.700928
134999 2024-01-01 02:29:59.960  home  250146926              5        2  2699.96  31.096189  -5.144443  0.694423

[3645000 rows x 9 columns]

### Formation detection per team

In [18]:
home_away = "home"  # Choose either home or away
team_data = input_data[input_data["team"] == home_away]
cpd = SoccerCPD(team_data)
cpd.run()

------------------------- Session 1 --------------------------
               session            start_dt              end_dt
player_period
1                    1 2024-09-28 05:00:00 2024-09-28 05:40:00

* Step 1: Frame-by-frame role assignment using RoleRep
- Cost after iteration 1: 5.998
- Cost after iteration 2: 5.958
- Cost after iteration 3: 5.966
Iteration finished since there are no significant changes.

* Step 2: FormCPD based on role-adjacency matrices
Applying g-segmentation to the sequence between 05:00:00 and 05:39:58...
Generalized edge-count statistic (a) :
  Estimated change-point location: 1739
  Test statistic: 1345.716
  Approximated p-value: 7.302627e-290
Generalized edge-count statistic (u) :
  Estimated change-point location: 446
  Test statistic: 749.1769
  Approximated p-value: 1.894357e-160
Change-point insignificant: The formation is not changed.

Detected formation change-points:
[]

* Step 3: RoleCPD per formation period based on role permutations

RoleCPD for the formation period 1:
Applying g-segmentation to the sequence between 05:00:00 and 05:39:58...
Generalized edge-count statistic (a) :
  Estimated change-point location: 1747
  Test statistic: 2782.471
  Approximated p-value: 0
Generalized edge-count statistic (u) :
  Estimated change-point location: 1747
  Test statistic: 10113.5
  Approximated p-value: 0
Change-point insignificant: The most frequent permutation is not changed.

Detected role change-points:
[]

------------------------- Session 2 --------------------------
               session            start_dt              end_dt
player_period
2                    2 2024-09-28 05:52:00 2024-09-28 06:05:45
3                    2 2024-09-28 06:05:45 2024-09-28 06:31:00

* Step 1: Frame-by-frame role assignment using RoleRep
- Cost after iteration 1: 6.009
- Cost after iteration 2: 5.902
- Cost after iteration 3: 5.896
- Cost after iteration 4: 5.894
Iteration finished since there are no significant changes.

* Step 2: FormCPD based on role-adjacency matrices
Applying g-segmentation to the sequence between 05:52:00 and 06:30:59...
Generalized edge-count statistic (a) :
  Estimated change-point location: 721
  Test statistic: 2308.296
  Approximated p-value: 0
Generalized edge-count statistic (u) :
  Estimated change-point location: 790
  Test statistic: 7484.12
  Approximated p-value: 0
A significant fine-tuned change-point at 06:05:45.

Applying g-segmentation to the sequence between 05:52:00 and 06:05:45...
Generalized edge-count statistic (a) :
  Estimated change-point location: 711
  Test statistic: 779.8154
  Approximated p-value: 2.332694e-167
Generalized edge-count statistic (u) :
  Estimated change-point location: 711
  Test statistic: 2903.527
  Approximated p-value: 0
Change-point insignificant: One of the periods has not enough duration.

Applying g-segmentation to the sequence between 06:05:45 and 06:30:59...
Generalized edge-count statistic (a) :
  Estimated change-point location: 151
  Test statistic: 718.8215
  Approximated p-value: 5.791988e-154
Generalized edge-count statistic (u) :
  Estimated change-point location: 879
  Test statistic: 679.4637
  Approximated p-value: 1.985694e-145
Change-point insignificant: One of the periods has not enough duration.

Detected formation change-points:
[Timestamp('2024-09-28 06:05:45')]

* Step 3: RoleCPD per formation period based on role permutations

RoleCPD for the formation period 2:
Applying g-segmentation to the sequence between 05:52:00 and 06:05:45...
Generalized edge-count statistic (a) :
  Estimated change-point location: 711
  Test statistic: 1540.115
  Approximated p-value: 0
Generalized edge-count statistic (u) :
  Estimated change-point location: 711
  Test statistic: 4074.457
  Approximated p-value: 0
Change-point insignificant: One of the periods has not enough duration.

Detected role change-points:
[]

RoleCPD for the formation period 3:
Applying g-segmentation to the sequence between 06:05:45 and 06:30:59...
Generalized edge-count statistic (a) :
  Estimated change-point location: 151
  Test statistic: 6086.208
  Approximated p-value: 0
Generalized edge-count statistic (u) :
  Estimated change-point location: 343
  Test statistic: 10108.47
  Approximated p-value: 0
Change-point insignificant: One of the periods has not enough duration.

Detected role change-points:
[]

-------------------------------------------------------------------------
Formation Periods:
   session            start_dt              end_dt  duration
0        1 2024-09-28 05:00:00 2024-09-28 05:40:00    2400.0
1        2 2024-09-28 05:52:00 2024-09-28 06:05:45     825.0
2        2 2024-09-28 06:05:45 2024-09-28 06:31:00    1515.0

Role Periods:
   role_period  session            start_dt              end_dt  duration
0            1        1 2024-09-28 05:00:00 2024-09-28 05:40:00    2400.0
1            2        2 2024-09-28 05:52:00 2024-09-28 06:05:45     825.0
2            3        2 2024-09-28 06:05:45 2024-09-28 06:31:00    1515.0

### Label assignment using precomputed formation clusters

In [20]:
benchmark_forms = pd.read_pickle("data/benchmark_forms.pkl")
benchmark_roles = pd.read_csv("data/benchmark_roles.csv", header=0)
# cpd.label_roles(role_benchmarks, form_benchmarks)

form_labels = {1: "433", 2: "433", 3: "41212"}
cpd.label_roles(benchmark_roles, form_labels=form_labels)
cpd.role_labels

   1    2   3    4    5    6    7    8    9   10
1  LB  RCM  RB   LM  RCB  LCB  LCM  CDM   RM  CF
2  LB  RCM  RB   LM  RCB  LCB  LCM  CDM   RM  CF
3  LB  RCM  RB  LCM  RCB  LCB  CAM  CDM  RCF  CF

In [21]:
cpd.form_periods

   form_period  session            start_dt              end_dt  duration                                            node_xy                                           edge_mat  label
0            1        1 2024-09-28 05:00:00 2024-09-28 05:40:00    2400.0  [[-4.5737, 19.1023], [3.3782, -6.6895], [-7.30...  [[0.0, 0.015, 0.088, 0.978, 0.2531, 0.9987, 0....    433
1            2        2 2024-09-28 05:52:00 2024-09-28 06:05:45     825.0  [[-6.1285, 16.2296], [2.422, -6.4583], [-6.712...  [[0.0, 0.0329, 0.1403, 0.9595, 0.4046, 0.9886,...    433
2            3        2 2024-09-28 06:05:45 2024-09-28 06:31:00    1515.0  [[-5.3813, 17.2437], [1.0982, -7.6291], [-8.50...  [[0.0, 0.0228, 0.0394, 0.9537, 0.2514, 0.9924,...  41212

### Saving results and visualization

In [7]:
activity_id = home_id if home_away == "home" else away_id

In [9]:
cpd.save_stats(match_id=activity_id)

'./data/gseg_avg/form_summary/sample_away.pkl' saving done.
'./data/gseg_avg/role_summary/sample_away.csv' saving done.
'./data/gseg_avg/role_seq/sample_away.csv' saving done.

In [23]:
cpd.visualize(match_id=activity_id, role_labels=cpd.role_labels, save=True)

'./data/gseg_avg/viz_report/79852.png' saving done.